/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Product;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abby
 */
public class ItemOrdering extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form ItemOrdering
     */
    public ItemOrdering() {
        initComponents();
        
        txtEspresso.addMouseListener(this);
        txtAmericano.addMouseListener(this);
        txtCappuccino.addMouseListener(this);
        txtLatte.addMouseListener(this);
        txtMacchiato.addMouseListener(this);
        txtAffogato.addMouseListener(this);
        txtCroissant.addMouseListener(this);
        txtCinnamonRoll.addMouseListener(this);
        txtMacaron.addMouseListener(this);
        txtBaklava.addMouseListener(this);
        txtLechePlant.addMouseListener(this);
        txtCassavaCake.addMouseListener(this);
        txtChicken.addMouseListener(this);
        txtGrilledCheese.addMouseListener(this);
        txtTuna.addMouseListener(this);
        txtEgg.addMouseListener(this);
        txtClub.addMouseListener(this);
        txtVeggie.addMouseListener(this);
        txtBlack.addMouseListener(this);
        txtGreen.addMouseListener(this);
        txtMatcha.addMouseListener(this);
        txtBlue.addMouseListener(this);
        txtOolong.addMouseListener(this);
        txtJasmine.addMouseListener(this);
        txtOrange.addMouseListener(this);
        txtApple.addMouseListener(this);
        txtPineapple.addMouseListener(this);
        txtGrape.addMouseListener(this);
        txtLemon.addMouseListener(this);
        txtMango.addMouseListener(this);
    }
    DefaultTableModel model = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        txtCappuccino = new javax.swing.JLabel();
        txtEspresso = new javax.swing.JLabel();
        txtAmericano = new javax.swing.JLabel();
        txtAffogato = new javax.swing.JLabel();
        txtLatte = new javax.swing.JLabel();
        txtMacchiato = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtBaklava = new javax.swing.JLabel();
        txtCroissant = new javax.swing.JLabel();
        txtMacaron = new javax.swing.JLabel();
        txtCinnamonRoll = new javax.swing.JLabel();
        txtCassavaCake = new javax.swing.JLabel();
        txtLechePlant = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtClub = new javax.swing.JLabel();
        txtChicken = new javax.swing.JLabel();
        txtGrilledCheese = new javax.swing.JLabel();
        txtTuna = new javax.swing.JLabel();
        txtEgg = new javax.swing.JLabel();
        txtVeggie = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtJasmine = new javax.swing.JLabel();
        txtBlack = new javax.swing.JLabel();
        txtGreen = new javax.swing.JLabel();
        txtMatcha = new javax.swing.JLabel();
        txtBlue = new javax.swing.JLabel();
        txtOolong = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtApple = new javax.swing.JLabel();
        txtLemon = new javax.swing.JLabel();
        txtOrange = new javax.swing.JLabel();
        txtPineapple = new javax.swing.JLabel();
        txtMango = new javax.swing.JLabel();
        txtGrape = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        txtSub = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("WELCOME to Tea and Coffee Shop Sales System!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        txtCappuccino.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\CUPPACCINOOOO.jpg")); // NOI18N
        txtCappuccino.setText("jLabel2");

        txtEspresso.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\ESPRESSOOOO.jpg")); // NOI18N
        txtEspresso.setText("jLabel2");

        txtAmericano.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\AMERICAOOO.jpg")); // NOI18N
        txtAmericano.setText("jLabel2");

        txtAffogato.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\AFFOGATO.jpg")); // NOI18N
        txtAffogato.setText("jLabel2");

        txtLatte.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\LATTE.jpg")); // NOI18N
        txtLatte.setText("jLabel2");

        txtMacchiato.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\MACCHIATO.jpg")); // NOI18N
        txtMacchiato.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEspresso, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLatte, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAffogato, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(197, Short.MAX_VALUE)
                    .addComponent(txtMacchiato, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(193, 193, 193)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEspresso, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLatte, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAffogato, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(288, Short.MAX_VALUE)
                    .addComponent(txtMacchiato, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(46, 46, 46)))
        );

        jTabbedPane1.addTab("COFFEE", jPanel3);

        txtBaklava.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\OneDrive\\Desktop\\product\\buko pie.jpg")); // NOI18N
        txtBaklava.setText("jLabel2");

        txtCroissant.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\CROISSANT.jpg")); // NOI18N
        txtCroissant.setText("jLabel2");

        txtMacaron.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\OneDrive\\Desktop\\product\\macaron.jpg")); // NOI18N
        txtMacaron.setText("jLabel2");

        txtCinnamonRoll.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\CINNAMON ROLL.jpg")); // NOI18N
        txtCinnamonRoll.setText("jLabel2");

        txtCassavaCake.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\CASSAVA CAKE.jpg")); // NOI18N
        txtCassavaCake.setText("jLabel2");

        txtLechePlant.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\LECHE PLAN.jpg")); // NOI18N
        txtLechePlant.setText("jLabel2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtCroissant, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(txtCinnamonRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtBaklava, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtLechePlant, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMacaron, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCassavaCake, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCroissant, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCinnamonRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMacaron, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBaklava, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLechePlant, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCassavaCake, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        jTabbedPane1.addTab("PASTRIES", jPanel5);

        txtClub.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\CLUB SANDWICH.jpg")); // NOI18N
        txtClub.setText("jLabel2");

        txtChicken.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\OneDrive\\Desktop\\product\\chicken sandwich.jpg")); // NOI18N
        txtChicken.setText("jLabel2");

        txtGrilledCheese.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\OneDrive\\Desktop\\product\\egg sandwuch.jpg")); // NOI18N
        txtGrilledCheese.setText("jLabel2");

        txtTuna.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\OneDrive\\Desktop\\product\\tuna sandwich.jpg")); // NOI18N
        txtTuna.setText("jLabel2");

        txtEgg.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\VIGGIE SALAD.jpg")); // NOI18N
        txtEgg.setText("jLabel2");

        txtVeggie.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\GRILLED CHEESE.jpg")); // NOI18N
        txtVeggie.setText("jLabel2");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtChicken, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtGrilledCheese, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtEgg, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtClub, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTuna, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVeggie, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChicken, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGrilledCheese, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTuna, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClub, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEgg, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVeggie, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        jTabbedPane1.addTab("SANDWICHES", jPanel6);

        txtJasmine.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\JASMINE TEAAAA.jpg")); // NOI18N
        txtJasmine.setText("jLabel2");

        txtBlack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\blackTEA.jpg")); // NOI18N
        txtBlack.setText("jLabel2");

        txtGreen.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\OneDrive\\Desktop\\product\\lemon grass tea.jpg")); // NOI18N
        txtGreen.setText("jLabel2");

        txtMatcha.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\GREEEEN TEA.jpg")); // NOI18N
        txtMatcha.setText("jLabel2");

        txtBlue.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\BLUE TERNATEEE TEAAAA.jpg")); // NOI18N
        txtBlue.setText("jLabel2");

        txtOolong.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\OOOOKONG TEA.jpg")); // NOI18N
        txtOolong.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMatcha, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJasmine, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(199, 199, 199)
                    .addComponent(txtOolong, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGap(197, 197, 197)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatcha, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtJasmine, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(288, Short.MAX_VALUE)
                    .addComponent(txtOolong, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)))
        );

        jTabbedPane1.addTab("TEA", jPanel1);

        txtApple.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\APPLE.jpg")); // NOI18N
        txtApple.setText("jLabel2");

        txtLemon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\OneDrive\\Desktop\\product\\mango.jpg")); // NOI18N
        txtLemon.setText("jLabel2");

        txtOrange.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\ORANGE.jpg")); // NOI18N
        txtOrange.setText("jLabel2");

        txtPineapple.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\PINEAPPLE.jpg")); // NOI18N
        txtPineapple.setText("jLabel2");

        txtMango.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\MANGO.jpg")); // NOI18N
        txtMango.setText("jLabel2");

        txtGrape.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abby\\Downloads\\GRAPE.jpg")); // NOI18N
        txtGrape.setText("jLabel2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtOrange, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtApple, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtGrape, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLemon, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMango, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(366, Short.MAX_VALUE)
                    .addComponent(txtPineapple, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(24, 24, 24)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApple, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrange, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGrape, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLemon, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMango, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(txtPineapple, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(288, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("FRUIT JUICES", jPanel4);

        jTable1.setBackground(new java.awt.Color(217, 153, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM", "PRICE", "QUANTITY", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel32.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel32.setText("TOTAL: ");

        txtSub.setBackground(new java.awt.Color(255, 204, 255));
        txtSub.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        txtSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSub, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemOrdering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemOrdering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemOrdering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemOrdering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ItemOrdering().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txtAffogato;
    private javax.swing.JLabel txtAmericano;
    private javax.swing.JLabel txtApple;
    private javax.swing.JLabel txtBaklava;
    private javax.swing.JLabel txtBlack;
    private javax.swing.JLabel txtBlue;
    private javax.swing.JLabel txtCappuccino;
    private javax.swing.JLabel txtCassavaCake;
    private javax.swing.JLabel txtChicken;
    private javax.swing.JLabel txtCinnamonRoll;
    private javax.swing.JLabel txtClub;
    private javax.swing.JLabel txtCroissant;
    private javax.swing.JLabel txtEgg;
    private javax.swing.JLabel txtEspresso;
    private javax.swing.JLabel txtGrape;
    private javax.swing.JLabel txtGreen;
    private javax.swing.JLabel txtGrilledCheese;
    private javax.swing.JLabel txtJasmine;
    private javax.swing.JLabel txtLatte;
    private javax.swing.JLabel txtLechePlant;
    private javax.swing.JLabel txtLemon;
    private javax.swing.JLabel txtMacaron;
    private javax.swing.JLabel txtMacchiato;
    private javax.swing.JLabel txtMango;
    private javax.swing.JLabel txtMatcha;
    private javax.swing.JLabel txtOolong;
    private javax.swing.JLabel txtOrange;
    private javax.swing.JLabel txtPineapple;
    private javax.swing.JTextField txtSub;
    private javax.swing.JLabel txtTuna;
    private javax.swing.JLabel txtVeggie;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param e
     */
    @Override
   public void mouseClicked(MouseEvent e) {
    if (e.getSource() == txtEspresso) {
        String name = "Espresso";
        int price = 60;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
    } 
    
    else if (e.getSource() == txtAmericano) {
        String name = "Americano";
        int price = 50;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
    } 
    
    else if (e.getSource() == txtCappuccino) {
        String name = "Cappuccino";
        int price = 65;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
    } 
    
    else if (e.getSource() == txtLatte) {
        String name = "Latte";
        int price = 55;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
    } 
    
    else if (e.getSource() == txtMacchiato) {
        String name = "Macchiato";
        int price = 70;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty; 

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
    } 
    
    else if (e.getSource() == txtAffogato) {
        String name = "Affogato";
        int price = 80;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
    }
    
    else if (e.getSource() == txtCroissant) {
        String name = "Croissant";
        int price = 25;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
    }
    
    else if (e.getSource() == txtCinnamonRoll) {
        String name = "Cinnamon Roll";
        int price = 20;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
}
    
   else if (e.getSource() == txtMacaron) {
        String name = "Macaron";
        int price = 15;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
}
    
    else if (e.getSource() == txtBaklava) {
        String name = "Baklava";
        int price = 15;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
}
    
    else if (e.getSource() == txtLechePlant) {
        String name = "Leche Plan";
        int price = 60;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
}
    
    else if (e.getSource() == txtCassavaCake) {
        String name = "Cassava Cake";
        int price = 50;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
}
    
    else if (e.getSource() == txtChicken) {
        String name = "Chicken Sandwich";
        int price = 40;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
}
    
    else if (e.getSource() == txtGrilledCheese) {
        String name = "Grilled Cheese Sandwich";
        int price = 30;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
}
    
    else if (e.getSource() == txtTuna) {
        String name = "Tuna Sandwich";
        int price = 30;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
}
    
    else if (e.getSource() == txtEgg) {
        String name = "Egg Sandwich";
        int price = 20;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
}
    
    else if (e.getSource() == txtClub) {
        String name = "Club Sandwich";
        int price = 45;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
}
    
    else if (e.getSource() == txtVeggie) {
        String name = "Veggie Sandwich";
        int price = 50;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
}
    
    else if (e.getSource() == txtBlack) {
        String name = "Black Tea";
        int price = 20;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
}
    
     else if (e.getSource() == txtGreen) {
        String name = "Green Tea";
        int price = 20;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
}
    
    else if (e.getSource() == txtMatcha) {
        String name = "Matcha Tea";
        int price = 25;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
}
    
     else if (e.getSource() == txtBlue) {
        String name = "Blue Ternate Tea";
        int price = 15;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
   }
  
        else if (e.getSource() == txtOolong) {
        String name = "Oolong Tea";
        int price = 20;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
   }
  
    else if (e.getSource() == txtJasmine) {
        String name = "Jasmine Tea";
        int price = 30;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
   }
    
    else if (e.getSource() == txtOrange) {
        String name = "Orange Juice";
        int price = 15;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
   }
    
     else if (e.getSource() == txtApple) {
        String name = "Apple Juice";
        int price = 15;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
   }
    
    else if (e.getSource() == txtPineapple) {
        String name = "Pineapple Juice";
        int price = 15;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
   }
    
    else if (e.getSource() == txtGrape) {
        String name = "Grape Juice";
        int price = 15;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
   }
    
    else if (e.getSource() == txtLemon) {
        String name = "Lemon Juice";
        int price = 15;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
   }
    
    else if (e.getSource() == txtMango) {
        String name = "Mango Juice";
        int price = 15;
        int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity: "));
        int tot = price * qty;

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[] { name, price, qty, tot };
        tableModel.addRow(row);

        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtSub.setText(Integer.toString(sum));
   }
  
   }

    @Override
    public void mousePressed(MouseEvent e) {
        
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {
       
    }

    @Override
    public void mouseExited(MouseEvent e) {
    
    }
}
