package GUI;

import Control_Connector.AdminMarie;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class LogIn extends javax.swing.JFrame {

    AdminMarie marie = new AdminMarie();
    int xx, xy;
    DefaultTableModel model;
    public LogIn() {
        initComponents();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtLogin = new javax.swing.JButton();
        txtCancel = new javax.swing.JButton();
        txtDontHaveAnAccount = new javax.swing.JLabel();
        txtExit = new javax.swing.JLabel();
        txtShowPassword = new javax.swing.JCheckBox();
        txtSignUp = new javax.swing.JButton();
        txtForgotPassword = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Tea Bugs");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 190, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Username:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        txtUsername.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameKeyTyped(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 380, 35));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 380, 35));

        txtLogin.setBackground(new java.awt.Color(0, 204, 0));
        txtLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtLogin.setText("Login");
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 170, 40));

        txtCancel.setBackground(new java.awt.Color(255, 51, 0));
        txtCancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtCancel.setForeground(new java.awt.Color(255, 255, 255));
        txtCancel.setText("Cancel");
        txtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCancelActionPerformed(evt);
            }
        });
        getContentPane().add(txtCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 170, 40));

        txtDontHaveAnAccount.setText("Don't have an account?");
        getContentPane().add(txtDontHaveAnAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 140, -1));

        txtExit.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtExit.setText("x");
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
        });
        getContentPane().add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, -1, 28));

        txtShowPassword.setText("Show Password");
        txtShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtShowPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(txtShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));

        txtSignUp.setBackground(new java.awt.Color(255, 204, 204));
        txtSignUp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSignUp.setText("Sign up");
        txtSignUp.setBorder(null);
        txtSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(txtSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        txtForgotPassword.setBackground(new java.awt.Color(255, 204, 204));
        txtForgotPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtForgotPassword.setText("Forgot Password");
        txtForgotPassword.setBorder(null);
        txtForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtForgotPasswordMouseClicked(evt);
            }
        });
        txtForgotPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtForgotPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGIN BACKGROUND.jpg"))); // NOI18N
        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel7MouseDragged(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        if (isEmpty()){
            String username = txtUsername.getText().trim();
            String password = String.valueOf(txtPassword.getPassword());
            try {
                if (marie.getMaxRowAdminTable() !=1){
                    if(marie.login(username, password)){
                        JOptionPane.showConfirmDialog(this, "Login successful!");
                        new Homeframe().setVisible(true);
                        setVisible(false);
                    }else{
                        JOptionPane.showMessageDialog(this, "Incorrect username or password.","Login failed", 2);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "No admin in the admin table!\n You need to sign up first.","Login failed", 2);
                    try {
                        new SignUp().setVisible(true);
                    } catch (SQLException ex) {
                        Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    setVisible(false);
                }
            } catch (SQLException ex) {
                Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            }

        
        public boolean isEmpty(){
        if(txtUsername.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Username is required!", "Warning", 2);
            return false;
        }
        if(String.valueOf(txtPassword.getPassword()).isEmpty()){
            JOptionPane.showMessageDialog(this, "Password is required!", "Warning", 2);
            return false;
        }
        return true;
    }//GEN-LAST:event_txtLoginActionPerformed

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtForgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtForgotPasswordActionPerformed
       ForgotPassword fp = new ForgotPassword();
       fp.show();
       
       dispose();
    }//GEN-LAST:event_txtForgotPasswordActionPerformed

    private void txtSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSignUpActionPerformed
        try {
            SignUp su = new SignUp();
            su.show();
            
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtSignUpActionPerformed

    private void txtShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtShowPasswordMouseClicked
        // TODO add your handling code here:
        if (txtShowPassword.isSelected()){
            txtPassword.setEchoChar((char)0);
        }
        else{
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_txtShowPasswordMouseClicked

    private void txtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyTyped
        // TODO add your handling code here:
        char input = evt.getKeyChar();
        if (! (input < '0' || input > '9') && input != '\b') {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Username doesn't contain any number!", "Warning", 2);        
    }
    }//GEN-LAST:event_txtUsernameKeyTyped

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
        
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x -xx, y -xy);
    }//GEN-LAST:event_jLabel7MouseDragged

    private void txtForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtForgotPasswordMouseClicked
        try {
            new SignUp().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
       setVisible(false);
    }//GEN-LAST:event_txtForgotPasswordMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for(double i = 0.1; i <= 1.0; i += 0.1){
            String s = ""+i;
                float f = Float.parseFloat(s);
                this.setOpacity(f);
            try {
                Thread.sleep(40);
                
            } catch (InterruptedException ex) {
                Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void txtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_txtCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton txtCancel;
    private javax.swing.JLabel txtDontHaveAnAccount;
    private javax.swing.JLabel txtExit;
    private javax.swing.JButton txtForgotPassword;
    private javax.swing.JButton txtLogin;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JCheckBox txtShowPassword;
    private javax.swing.JButton txtSignUp;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private ForgotPassword ForgotPassword() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private SignUp SignUp() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
